# fly.toml for Fly.io deployment

app = "ddtimer"
primary_region = "cdg"

[build]
  image = "lancel00zz/facilitator-timer-app:latest"

[http_service]
  internal_port = 5050
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
