# fly.toml for facilitator container deployment

app = "ddtimer"
primary_region = "cdg"

[build]
  image = "lancel00zz/ddtimer:latest"

[http_service]
  internal_port = 5050
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  DD_ENV = "prod"
  DD_SERVICE = "ddtimer"
  DD_VERSION = "4.9"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
